### ISSUE TITLE
[bmi160_support.c] Watermark interrupts not enabled in bmi160_config_running_mode()

### ISSUE THREAD

**Issue by daviddyao** [BoschSensortec/BMI160_driver#2] opened 2015-08-09 23:09 UTC
The function **bmi160_config_running_mode()** configures the watermark interrupt for modes like STANDARD_UI_IMU_FIFO on pins INT1 & INT2 but doesn't actually enable the interrupt itself in the INT_EN[1] register. A call to **bmi160_set_intr_enable_1()** is needed to complete the configuration. For example:

```c
/* Enable FIFO water mark interrupts in INT_EN[1] */
bmi160_set_intr_enable_1(BMI160_FIFO_WM_ENABLE, BMI160_HEX_0_1_DATA);
```

**Comment by BoschSensortec** [comment] 2016-06-15 12:55
Thanks for your comments. The issue is addressed in the latest release.

**Closed by BoschSensortec** 2016-06-15 12:55 UTC
